// src/App.tsx
import * as React from 'react'
import { FC } from 'react'
import 'react-hot-loader/patch'
import { hot } from 'react-hot-loader/root'

import { ThemeConsumer, ThemeProvider } from '@ices/theme/react'
import ThemeSelect from './ThemeSelect'

const App: FC = function (props) {
  return (
    <ThemeProvider>
      <div style={{ margin: '16px' }}>
        <ThemeConsumer>
          {(theme) => (
            <label
              style={{
                paddingRight: '8px',
                color: theme === 'dark' ? '#c9d1d9' : '#24292e'
              }}
              htmlFor="react-theme-select"
            >
              Select Theme:
            </label>
          )}
        </ThemeConsumer>
        <ThemeSelect id="react-theme-select" />
        <div className="stage">{props.children}</div>
      </div>
    </ThemeProvider>
  )
}

export default hot(App)

// src/App.vue
<template>
  <div class="box">
    <label for="theme-select-vue" :style="labelStyle">Select Theme:</label>
    <ThemeSelect id="theme-select-vue" />
    <div class="stage">
      <slot />
    </div>
  </div>
</template>

<script>
import ThemeSelect from './ThemeSelect.vue'
import themeManager from '@ices/theme'

export default {
  name: 'App',
  components: { ThemeSelect },
  data() {
    return { theme: themeManager.theme }
  },
  computed: {
    labelStyle() {
      return { color: this.theme === 'dark' ? '#c9d1d9' : '#24292e' }
    }
  },
  mounted() {
    const handler = ({ data: { current } }) => {
      this.theme = current
    }
    this.unsubscribe = themeManager.subscribe('change', handler)
  },
  beforeDestroy() {
    if (this.unsubscribe) {
      this.unsubscribe()
    }
  }
}
</script>

<style scoped>
.box {
  margin: 16px;
}

label {
  padding-right: 8px;
}
</style>
