// src/ThemeSelect.vue
<template>
  <div class="theme-select">
    <select v-bind="$attrs" v-on="$listeners" v-model="theme">
      <option v-for="theme in themeList" :key="theme" :value="theme">
        {{ theme }}
      </option>
    </select>
  </div>
</template>

<script>
import themeManager from '@ices/theme'

export default {
  name: 'ThemeSelect',
  inheritAttrs: false,
  data() {
    return {
      themeList: themeManager.themeList,
      theme: localStorage.getItem('theme') || themeManager.theme
    }
  },
  watch: {
    theme(value) {
      themeManager.theme = value
    }
  },
  mounted() {
    const handler = ({ data: { current } }) => {
      this.theme = current
      localStorage.setItem('theme', current)
    }
    this.unsubscribe = themeManager.subscribe('change', handler)
  },
  beforeDestroy() {
    if (this.unsubscribe) {
      this.unsubscribe()
    }
  }
}
</script>

<style scoped>
.theme-select {
  display: inline-block;
}
</style>

// src/ThemeSelect.tsx
import * as React from 'react'
import {
  ChangeEventHandler,
  SelectHTMLAttributes,
  useCallback,
  VFC
} from 'react'
import { useTheme } from '@ices/theme/react'

type ThemeSelectProps = Pick<
  SelectHTMLAttributes<HTMLSelectElement>,
  'id' | 'name' | 'className' | 'style'
>
type ChangeHandlerType = ChangeEventHandler<HTMLSelectElement>

const ThemeSelect: VFC<ThemeSelectProps> = function (props) {
  const [theme, themeList, changeTheme] = useTheme(
    localStorage.getItem('theme') || ''
  )

  const handleChange = useCallback<ChangeHandlerType>((event) => {
    changeTheme(event.target.value).then((theme) => {
      localStorage.setItem('theme', theme)
    })
  }, [])

  return (
    <select {...props} value={theme} onChange={handleChange}>
      {themeList.map((theme) => (
        <option key={theme}>{theme}</option>
      ))}
    </select>
  )
}

export default ThemeSelect
